title: Shivank Pathak
description: My Personal Page
author: Shivank Pathak
logo: static/img/shivank_dp.png
github: https://github.com/shivank01
about: Pythonista,Machine Learning Enthusiast and Competitive Programmer

# baseurl: ""
url: "https://shivank01.github.io"

allowsearch: true

disqus_shortname: shivankpathak
google_analytics: UA-112671461-1

share:
  twitter_username: shivank__
 # fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


future: true
