title: Shivank Pathak
description: My Personal Page
author: Shivank Pathak
logo: /hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/shivank01
about: Pythonista,Machine Learning Enthusiast and Competitive Programmer

baseurl: "https://shivank01.github.io/"
url: ""

allowsearch: true

#disqus_shortname: aboutshivank
#google_analytics: UA-72862926-1

share:
  twitter_username: shivank__
 # fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]


future: true
