\LoadClass[11pt,a4paper,sans]{moderncv}
\moderncvstyle{banking} %options are casual(default),classic,oldstyle and banking

\moderncvcolor{blue} %color options are blue(default),orange,green,red,purple,grey and black

\name{Shivank}{Pathak}
\title{}
\address{J-001}{IIIT Bhubaneswar boys hostel}{751003,Bhubaneswar,Odisha(INDIA)}
\mobile{+91~798~568~4018}
\email{b416045@iiit-bh.ac.in}
\homepage{shivank01.github.io}
\social[github][github.com/shivank01]{shivank01}
\social[linkedin][www.linkedin.com/in/shivank-pathak-1a7895bb/]{Shivank Pathak}

%character encoding
\RequirePackage[utf8]{inputenc}
\RequirePackage{geometry}
\geometry{
left=15mm,
right=15mm,
top=10mm,
bottom=5mm,
}
